---
- name: Install Kibana
  become: true
  apt:
    name: kibana
    state: present

- name: Restart and enable Kibana service
  become: true
  service:
    name: kibana
    state: restarted
    enabled: true

- name: Check 5601 port
  wait_for:
    port: 5601
    delay: 10
