---
- name: Create Nginx server
  hosts: nginx
  tags:
    - nginx
  roles:
    - initialisation
    - nginx
    - node-exporter
    - nginx-exporter

- name: Create Prometheus server
  hosts: prometheus
  tags:
    - prometheus
  roles:
    - initialisation
    - prometheus

- name: Create Grafana server
  hosts: grafana
  tags:
    - grafana
  roles:
    - initialisation
    - grafana